### ISSUE TITLE
Question for $HASS_CONFIG for shell_command update_hass

### ISSUE THREAD

**Issue by genestealer** [dale3h/homeassistant-config#5]
On line 123 of [homeassistant-config/packages/utilities.yaml](https://github.com/dale3h/homeassistant-config/blob/3a67147a964f093fae209f8ea9ee1759a5421b39/packages/utilities.yaml)

You have the line:` /usr/bin/nohup $HASS_CONFIG/shell_scripts/update_hass.sh </dev/null >> $HASS_CONFIG/shell_scripts/update_hass.log 2>&1 &`

How are you retrieving the 

> $HASS_CONFIG

 path of 

> /home/homeassistant/.homeassistant

Is it from "HASS_CONFIG=/home/homeassistant/.homeassistant" in [secrets.sample.env](https://github.com/dale3h/homeassistant-config/blob/03b92891c64ba4cc5ad9626c858cd7e041b860ce/secrets.sample.env) ?

**Comment by dale3h** [comment]
@Genestealer Yes, it is being retrieved from the "live" version of that `.env` file (`/home/homeassistant/.homeassistant/secrets.env`). I have modified the `home-assistant.service` file to automatically load the environment file prior to starting Home Assistant:

```
[Unit]
Description=Home Assistant
After=network.target

[Service]
Type=simple
User=homeassistant
EnvironmentFile=/home/homeassistant/.homeassistant/secrets.env
ExecStart=/srv/homeassistant/bin/hass -c "$HASS_CONFIG"
SendSIGKILL=no

[Install]
WantedBy=multi-user.target
```
